export const SET_TSHIRT_STATE = "SET_TSHIRT_STATE";
export const SET_JEANS_STATE = "SET_JEANS_STATE";
export const SET_MOBILE_STATE = "SET_MOBILE_STATE";
export const SET_EARPHONES_STATE = "SET_EARPHONES_STATE";
export const SET_MAC_STATE = "SET_MAC_STATE";
